name: Amethy-Terminal
version: 1.0.1
main: io.wany.amethy.terminal.bukkit.AmethyTerminal

description: Amethy Terminal Node Plugin for Bukkit Servers. Provides remote terminal for Minecraft servers in web.
author: Wany
website: https://amethy.wany.io

api-version: 1.14
loadbefore:
  - Amethy
  - CoreProtect
  - Cucumbery
  - Essentials
  - HolographicDisplays
  - LuckPerms
  - mcMMO
  - NoteBlockAPI
  - PlugMan
  - ProtocolLib
  - QuickShop
  - Vault
  - VoxelSniper
  - WorldEdit
  - WorldGuard

commands:
  amethyterminal:
    permission: amethy.terminal.command.amethyterminal
    usage: '/<command> (version|reload|debug|update|updater)'
    aliases: [at, aterm]
